networks:
  postgres-todo-app-network:
    driver: bridge

services:
  postgres:
    networks:
      - postgres-todo-app-network
    image: bitnami/postgresql:latest
    environment:
      - 'POSTGRESQL_DATABASE=inst'
      - 'POSTGRESQL_USERNAME=admin'
      - 'POSTGRESQL_PASSWORD=admin'

  app:
    depends_on:
      - postgres
    networks:
      - postgres-todo-app-network
    ports:
      - "8080:8080"
    build: .
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres:5432/inst'