networks:
  postgres-todo-app-network:
    driver: bridge

services:
  postgres:
    networks:
      - postgres-todo-app-network
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=inst'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'

  app:
    depends_on:
      - postgres
    networks:
      - postgres-todo-app-network
    ports:
      - "8080:8080"
    build: .