spring:
  application:
    name: to-do-list
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inst
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: public
  flyway:
    default-schema: public

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /swagger-docs

system:
  expiration-time: 30
  key-size: 2048